create table base_transacciones_alignet
(ID BIGINT IDENTITY(1,1),
NUMERO_PEDIDO VARCHAR(15),
ESTADO_TRANSACCION VARCHAR(20),
COMERCIO VARCHAR(50),
PAN VARCHAR(50),
MONTO VARCHAR(12),
FECHA_PEDIDO VARCHAR(20),
VCI VARCHAR(5),
TITULAR VARCHAR(100),
EMAIL VARCHAR(100),
CODIGO_AUTORIZACION VARCHAR(20),
MARCA_TARJETA VARCHAR(20),
TIPO_TARJETA VARCHAR(20),
BANCO VARCHAR(20),
CODIGO_UNICO VARCHAR(50),
ORDEN_COMPRA VARCHAR(50),
ASL  VARCHAR(50),
CANAL VARCHAR(50),
ESTADO_OPERACION INT,
FECHA_OPERACION DATETIME)


